name: Deploy Frontend

on:
  push:
    branches: [main]  # or 'master' or any branch you use

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Match your project version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Example: Deploy to GitHub Pages, S3, Vercel, etc.
      # Add your specific deployment steps here
