name: Build and Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Make gradlew executable
      run: chmod +x ./backend/musicapp/gradlew

    - name: Build backend with Gradle
      working-directory: ./backend/musicapp
      run: ./gradlew build
