name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle wrapper
        working-directory: backend/musicapp
        run: ./gradlew build

      # Add deployment steps here, for example:
      # - name: Deploy backend
      #   run: your deployment commands (e.g., SSH, copy files, Docker build & push)
