name: Deploy React Frontend

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred Node version

      - name: Install dependencies
        working-directory: ./music-app  # Change if your react app folder is different
        run: npm install

      - name: Build React app
        working-directory: ./music-app
        run: npm run build

      # Example: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./music-app/build
